
* Deal with long responses (connection timeouts?)
======================================================================
ERROR: test_getLookupByGenomeName (test.test_ensemblrest.EnsemblGenomeRest)
Testing Lookup by genome name GET method
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_ensemblrest.py", line 1820, in test_getLookupByGenomeName
    test = self.EnsEMBL.getLookupByGenomeName(name="campylobacter_jejuni_subsp_jejuni_bh_01_0142")
  File "ensemblrest/ensemblrest.py", line 128, in <lambda>
    return lambda **kwargs: self.call_api_func(api_call, api_table, **kwargs)
  File "ensemblrest/ensemblrest.py", line 178, in call_api_func
    resp = self.__get_response()
  File "ensemblrest/ensemblrest.py", line 221, in __get_response
    resp = self.session.get(self.last_url, headers = self.last_headers, params=self.last_params, timeout=self.timeout)
  File "/home/paolo/Projects/pyEnsemblRest/env/local/lib/python2.7/site-packages/requests/sessions.py", line 347, in get
    return self.request('GET', url, **kwargs)
  File "/home/paolo/Projects/pyEnsemblRest/env/local/lib/python2.7/site-packages/requests/sessions.py", line 335, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/paolo/Projects/pyEnsemblRest/env/local/lib/python2.7/site-packages/requests/sessions.py", line 438, in send
    r = adapter.send(request, **kwargs)
  File "/home/paolo/Projects/pyEnsemblRest/env/local/lib/python2.7/site-packages/requests/adapters.py", line 333, in send
    raise Timeout(e)
Timeout: HTTPConnectionPool(host='rest.ensemblgenomes.org', port=80): Request timed out. (timeout=5)
